keys:
  - &admin_jo age1ma7y9pzj5dk04j3jvjde3esfm6led6duludqk375k7hz93jc5a2scmw3ve
  - &machine_harvest age15qk2hwshn3wrqez9t7wgunyucu9fgdn3lpdr6k83ah2a5tvt793sg2sdn2
  - &machine_hiraeth age1n2q78sfsycx533vq5umcntpe3049c0gp92d38a4307zndylppv4qfdqshc
  - &machine_music age1uhrrllkednk9vn33mpc9hds5efa3nl42d95474p4cfl6p5h3k3zq8xuqfs
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *admin_jo
      - *machine_harvest
      - *machine_hiraeth
      - *machine_music