#ENC[AES256_GCM,data:u3Yna5Kq0k/puGCfpcYZa9a5JrVOK0y/zXcGllmkmg2b9FUCiDdWVr0JeIC0xSB1,iv:OMg4BoD3qTNSsFnb1opKOmRrMMLcJDBpmmqSjyvHkwQ=,tag:S8TDS3Ks9SSyEY8XY5l5Ww==,type:comment]
#ENC[AES256_GCM,data:u1eVHtG0ywlmfo2jrNNmBF84z1+LQi5xMQ==,iv:+tozwABJzRaqE9hnnqfu0uipCC2jFEwN+reJ3/f+sY4=,tag:DmV0gk7P6/rLV5NxErZwTg==,type:comment]
borgmatic: ENC[AES256_GCM,data:6VbSS0/iUeCo5XIZhrE=,iv:fAzqd7T++WR+G1QYNpfD7iAsxr2hWChqBi6hDn5CNjk=,tag:TC0MMGDM2u4EGCDWy73dhg==,type:str]
freshrss:
    jtremesay:
        password: ENC[AES256_GCM,data:xawUVDBUbfG7eFZw,iv:ekHWL5iVWIshwlTZI26CtRgl8jAwdiI1dK5Az6PmK/c=,tag:SWQul0zYaShL7jKJ0AMixw==,type:str]
nextcloud:
    jtremesay:
        password: ENC[AES256_GCM,data:rai+G6ngASZRFz0s8Vs=,iv:gYLmYIVGbh2A+IkO9zVeToF3aAsl0ZwyeEeucIToOLs=,tag:Z9LF8r/sCjYl8ubhJn/4wA==,type:str]
sops:
    age:
        - recipient: age1ma7y9pzj5dk04j3jvjde3esfm6led6duludqk375k7hz93jc5a2scmw3ve
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZU05JTUtoRWZjdTVwY0Z2
            a0VmRll4ZHBGVjVyTENPZ0ZwMG12b2NUV1VZClJlaTVxS21sdzRqM0hOSDZvZmhz
            d2FnSHdxM3N0Y0kxTnlrcnZkeC9YV0EKLS0tIFVKUEdIZGpnKzJFdUNtUkpIL3Vk
            M0Y1VzdXRFc4NW1KMzIvM2xPblBkdkUKBWmZYTIUlA8DN3W+2SHUSojicNRf/ByH
            dME3IUk/WJlNDCQ2fg0mFNfeypS3xZXwjZFNpVFu1FwhyO5l1Yb81A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n2q78sfsycx533vq5umcntpe3049c0gp92d38a4307zndylppv4qfdqshc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTC9Qd1V4V1B4RjhLRjJn
            b0JPZzdvL055UWVBTFZrM3hSNDEvSXF2cmcwCm1yS3Q1UUZLVXBPTndXeFVHWmpr
            bE1kVHVndFk2K2t2VnUrUlBROU1pNjgKLS0tIDNGUlowK1lQTmpFWFkwRFQrN3pU
            a1VhcXg1REtwNVZGWUNjYlExbGtKc0UKmonKk8+B+CjbQrgdMuBhv4smTmKdjI+L
            b0p2+kqmqMKeO8TERo2ArAm3349RxgN9rFZQV3bDvmGQEq1x6w5W4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T08:52:49Z"
    mac: ENC[AES256_GCM,data:R3IaLYc0GA1MvTRvA5i8uOZmzQIteDbiE6Aet8cWov7b1DbcuVnXqS8hP+hYk0qVYQydb7G3YBX296xp8QGIqakVj+Dxpm9SMGiUCFuWNhZkoAb/UgblejjDYX+vC9LBf+bZUy179lPVT3lKai8teIvAeO1cNoVqyG10zZuh97M=,iv:mRe2OyH9opSjiEy8HzIRHRc/i8kjupuJzExvkH1OrHM=,tag:ALgd4bo1QzPKPp0lzjitEw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
