#ENC[AES256_GCM,data:u3Yna5Kq0k/puGCfpcYZa9a5JrVOK0y/zXcGllmkmg2b9FUCiDdWVr0JeIC0xSB1,iv:OMg4BoD3qTNSsFnb1opKOmRrMMLcJDBpmmqSjyvHkwQ=,tag:S8TDS3Ks9SSyEY8XY5l5Ww==,type:comment]
#ENC[AES256_GCM,data:u1eVHtG0ywlmfo2jrNNmBF84z1+LQi5xMQ==,iv:+tozwABJzRaqE9hnnqfu0uipCC2jFEwN+reJ3/f+sY4=,tag:DmV0gk7P6/rLV5NxErZwTg==,type:comment]
tailscale:
    auth_key: ENC[AES256_GCM,data:TTJRT+rzbl3XIolpXZ5YfKsfjKPI5iNDWpJt/GcG1Dtplg/1eExwa9tAjZHHYWuWbN1nGyR18e2Ugblz5A==,iv:FdYHe08gKSdfc/7Yqv8RUPPaF3TbiHmsVxVA4DreSio=,tag:huFZwgAYoH5et+YU7P7isw==,type:str]
borgmatic: ENC[AES256_GCM,data:6VbSS0/iUeCo5XIZhrE=,iv:fAzqd7T++WR+G1QYNpfD7iAsxr2hWChqBi6hDn5CNjk=,tag:TC0MMGDM2u4EGCDWy73dhg==,type:str]
freshrss:
    jtremesay:
        password: ENC[AES256_GCM,data:xawUVDBUbfG7eFZw,iv:ekHWL5iVWIshwlTZI26CtRgl8jAwdiI1dK5Az6PmK/c=,tag:SWQul0zYaShL7jKJ0AMixw==,type:str]
nextcloud:
    jtremesay:
        password: ENC[AES256_GCM,data:rai+G6ngASZRFz0s8Vs=,iv:gYLmYIVGbh2A+IkO9zVeToF3aAsl0ZwyeEeucIToOLs=,tag:Z9LF8r/sCjYl8ubhJn/4wA==,type:str]
sops:
    age:
        - recipient: age1ma7y9pzj5dk04j3jvjde3esfm6led6duludqk375k7hz93jc5a2scmw3ve
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VnduUUpqTTcxbzhSWDFw
            dSszelZLMjMxMzd5NnhBVUlWUmpoL2lBdXdFClp1RzNlZHZNMFRqU3NiYTFLVWEv
            NkJ2R3dLNloxMW1PTEd3czhraTNtMGsKLS0tIHMzK2dJSEtRNE12UE9rUVYzZVEr
            VFI1SFVwdFR4ZjVnQTY3WlNtUDZxcDAKEf/cfD21JkokvxybEJyQ0gdX/v2g9M4U
            BDEvoyPBCNkV8YZ+SfLZvk5+5OtVGkpLNtxJHEK/Io1gt0S18bT5Aw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ejn9t5mf6rmg3v708ejpdmjvrep3tspwx5tnlwkmepexzpt9349qrg7wq6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaalh5ZkNKVWg3eVVUVWZQ
            R1VkaVZHOXVTYXlRMkl3Y0FFNXRtSFVQQkNZClNDMmVzNldhS3FabWlzVFJBcTIy
            UkQwcHZ3WU5aSFZ5NzNGZC9Ra28yOUUKLS0tIG1SMjZ5TUp6YzBRSStJZXJnWVFY
            Wi9mekVTb0VKUHFUdmZ6Tk9vNW16SncKdyIKY65UMJ/90jaR8ODuD6HV856d0goW
            12bOw+BxaxJmeFGD4WikwRTAYEmDVFm4xZ3q2d1jV+MAl90kNFtw4Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16z5lmvjvgsmtktqmpaz8x89nqg793fwzn274xcgz08kqa3tq3c9sr0nmyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsb1hqc3FVVlpKVGxGelVW
            czBaUU01OXZ2Zi8yUmRyVmk4MFg3cFhLZHhZCjcrREhDUEl3b0EzTWoxRVorVVdP
            UGxGYnpZQ01zNFBpMGNEUmx3SjlCYXcKLS0tIEhUS1dIMlkwU3lDeldWMllpam1J
            S25YRXBoRE9SWHUzNTBuM0NhZnYvUmcKYPGVG66tlf5OYQ9nAlUaZmqwCUnUrtdF
            y7npb7+FtDzh5EQfvy8FHi5ulfphxtMjJmHTbrmIqCZh/YWqhgkrBg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n2q78sfsycx533vq5umcntpe3049c0gp92d38a4307zndylppv4qfdqshc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRN3ZoVi9QYUVRcFk0N0pM
            VmFXOFEzQloxWTFYMjY0L3FHVTN6dlZGVkRNClFwN3BkR25VRHRDMmc0TWtqaUU1
            ZDU4SkVQaHNxcWd2SmZHV3BkYis0bzQKLS0tIEdUb1lhby9HbUdqRU9sR3NRa1Jr
            T3dUMTNKZTJMOFEwNTAvYkZRbjBFL3MKrOm94vjKVK+z6mEdQQK+81SGXeOY0j6E
            dcRcXcdlc7iweuX39/ssMekC2ilrv0YIbWD1tYEz+13AboVPU8cXrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-23T09:43:43Z"
    mac: ENC[AES256_GCM,data:urvqJjkPdPlXzYKzKdv+EYsEzwJB8NZ48zPmqDYavNm/LibA0ETbkZiVsHOZHvC3OlZUN/LCZnL6ip0ObXYDQA77f0nnySTevNrYYIam+LXUSZPk7dgUIbV1Z7ZYKV9+KCDXIT0OxMXzOoJUzZiVOPIluCxaCepjgIN8Hj2lCYo=,iv:CTBvLl6xMqem6nnwvM71YmFX9SdVOVlzpoWH3srUMpw=,tag:wJ83DubRq5zvnq6bmVx/2Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
