borgmatic: ENC[AES256_GCM,data:6VbSS0/iUeCo5XIZhrE=,iv:fAzqd7T++WR+G1QYNpfD7iAsxr2hWChqBi6hDn5CNjk=,tag:TC0MMGDM2u4EGCDWy73dhg==,type:str]
freshrss: ENC[AES256_GCM,data:tsm+SNZseNnkbU0m,iv:0ErN3RjavS9Tk4DhuOScu7Q2xQmtIFlsomcY/MP1A3c=,tag:JNqfra0lRV++Fr9I9kTpMA==,type:str]
matrix:
    registration_shared_secret: ENC[AES256_GCM,data:x0RVLucqEajAJPTYPRs=,iv:Bgr2ISXi7Xbs/dXJcu+TULYbl6fBtK78dfSkZGygrfA=,tag:eDB9/B4fjGexBwBjQgYs3g==,type:str]
nextcloud: ENC[AES256_GCM,data:ut4uDeMko05E0rQIhAc=,iv:N41xEhEWH1fCyt1y5aHqzyxBKGEoYiSJuNXFdZWUEPE=,tag:8fNLbaeCcrN9RTueK1BXGA==,type:str]
wifi: ENC[AES256_GCM,data:+nb1crT7iU35iB77hu1qqUCFJn56k9hi3t/B4ipZ,iv:ohg8EFpknbnFZtLYqP5L+rQxT8YSHtX3oqMzqDK8LNA=,tag:LuPMmM6firUqyDye3Ep5wg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoM3dVNkhQTFlwVUY2WHVY
            WHkyQ1laWGZ5N1piZDZ6eEJZSVl1SlF0V0dVCks2SFRxTjNLZVppNjR3SDdBVm8v
            S2NxK0pwTXg0YVdoRXRnM05hekRWaEkKLS0tIEF1MUhOWkkvVVhUK2dWcDg3d1M5
            WmYyTnoySFl0ZDJFK2QyN0hYdm16WUUKWtu95LUMi/e9/HNUnEpFvv7gonMoiLob
            I6ZMczcx8ivjXpm1ic10D3bUS0+uwQ/6fzxa8to1PlCqmmhtkzw7Sw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ma7y9pzj5dk04j3jvjde3esfm6led6duludqk375k7hz93jc5a2scmw3ve
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvL0YwbUI3RWpndXFlR2R6
            R2tzOHA0RURIMFNKQkxCUmJLaG9zckdYODNzCklvcWF2cEVZeWFwVS80UUtvOHJs
            RzIrK1QzdVFHUlQrOUJtbFpvNDB0QmsKLS0tIEZFV1hzUFREWXRzOWJkS0dRbzZo
            NGt5RmlxYkJWeElFNWw3ekd3UTZocm8KVmr6ysayWg0W9Zdgv6aq3K7nsXiF9Fbv
            C8qCH9vXQnqnEfUN10IEuxHpe/NZSWnhFf8U7cZp/PYMDX6EOhxdNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15qk2hwshn3wrqez9t7wgunyucu9fgdn3lpdr6k83ah2a5tvt793sg2sdn2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3QmdZUVFyVGJzekx1RHB3
            UzUwWWdNWHVzUVEyM2JpV3hIa0REVWd5SmxzCkgyWnhxWDJZUnEzVSsyUW9tRHd2
            eHIwVmp6UmpHU2FuV0xzZ2l4MkhSVkUKLS0tIDlQQnRJakJSbTBYZEFScVdidkpW
            dlB0ZktRbzE2eUVuY0pyOXpla1lGWHcKCqjzJETs2iZnzDT3SpzQ9m3ANs5Lox7K
            CtDOef1Y69KC70/U3CBDoKbhbRTRTbgBesumOBpmBih6T+/SCLFiIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2q78sfsycx533vq5umcntpe3049c0gp92d38a4307zndylppv4qfdqshc
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETGp6VWJEdzFuZFZWUWRM
            K3NKWTNOUWJWTVRFNlNFK0JKNG82TEUxeVVJCjVBakdnWkoyU0tEREg1NktPaFli
            eitsdk4xdFdmdWFXYWFOc3RZT2ZNN1EKLS0tIGlKZ0M1VVlZYy9OZEUvc1RBVkNt
            NWFDcUlSTEtLREkyWW4wWlBuYkZ4NUkKzYPv4SicWCj2l+YbGuH9C+SD/aHm+9/h
            xdhdV/BBbAniFJZQND9XEgexaMXm8AyOvyG/Z07+mTtzMU6CsD3RHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uhrrllkednk9vn33mpc9hds5efa3nl42d95474p4cfl6p5h3k3zq8xuqfs
    lastmodified: "2026-05-23T11:20:26Z"
    mac: ENC[AES256_GCM,data:D5HqGEdclN1mEvj7R2TfQhVfLS42gf6EXpDEpUiJKCfzsTE65HAtkIxtlLYaGIce2AxG8GMQJOVw7OEBNkjMOwncKGf/ED3UNuQQ5upBjHfLUN/pas9MezT8xV/RsYdxslQSfercGbBvhA/m7V00F2cDPCsR08r9jGh3iPsktbM=,iv:SNjx+QieO5Zvk7fkX9l9RByc+hRo8vOAWmd0GJd3Vwk=,tag:UihzdilLAsTQbCN+wUUGRA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
