#ENC[AES256_GCM,data:u3Yna5Kq0k/puGCfpcYZa9a5JrVOK0y/zXcGllmkmg2b9FUCiDdWVr0JeIC0xSB1,iv:OMg4BoD3qTNSsFnb1opKOmRrMMLcJDBpmmqSjyvHkwQ=,tag:S8TDS3Ks9SSyEY8XY5l5Ww==,type:comment]
#ENC[AES256_GCM,data:u1eVHtG0ywlmfo2jrNNmBF84z1+LQi5xMQ==,iv:+tozwABJzRaqE9hnnqfu0uipCC2jFEwN+reJ3/f+sY4=,tag:DmV0gk7P6/rLV5NxErZwTg==,type:comment]
borgmatic: ENC[AES256_GCM,data:6VbSS0/iUeCo5XIZhrE=,iv:fAzqd7T++WR+G1QYNpfD7iAsxr2hWChqBi6hDn5CNjk=,tag:TC0MMGDM2u4EGCDWy73dhg==,type:str]
freshrss:
    jtremesay:
        password: ENC[AES256_GCM,data:xawUVDBUbfG7eFZw,iv:ekHWL5iVWIshwlTZI26CtRgl8jAwdiI1dK5Az6PmK/c=,tag:SWQul0zYaShL7jKJ0AMixw==,type:str]
nextcloud:
    jtremesay:
        password: ENC[AES256_GCM,data:rai+G6ngASZRFz0s8Vs=,iv:gYLmYIVGbh2A+IkO9zVeToF3aAsl0ZwyeEeucIToOLs=,tag:Z9LF8r/sCjYl8ubhJn/4wA==,type:str]
sops:
    age:
        - recipient: age1ma7y9pzj5dk04j3jvjde3esfm6led6duludqk375k7hz93jc5a2scmw3ve
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbzRTdTFlcmxyWkxKbnpk
            a0U1cXpEOURGOEJqemR3aVAzL3VBWjdPOEZFClBZQmNNUzl1UU5oOUwyckdkaWlC
            K0I3OWxqa21FNjBWYWI0ZW9tcjhRWEEKLS0tIHc3RzZ1THB3eEdmQ1RlY3ZpWmpC
            L2JETnB3dzF1QTBSekdSbUYySS9HbjAKRgkjZRkOYG0JV6Bt7lc17oe0xKQPiJkU
            b21yUP80+o0+SNStidVc1or9Isg5UVXdwae/+CDiurSVHo93jfH/Mw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n2q78sfsycx533vq5umcntpe3049c0gp92d38a4307zndylppv4qfdqshc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eWIzeC9ZVEF0L25xWXVY
            eUNkbkpxVGsyTmNOSDUvSGRJem9QRVdCb0F3CnhNRC9NYzIrZmVWUmkwTk1Dd0VU
            YUF6dWhYc3BqQlFFNHpDK0pVUG1LUHMKLS0tIFZLcWY5Z2dsOVlXNVd5dmF5dEtz
            NmlLQ2lwUVVUcUZ3cXZkN2RnU1BBUWMKzkCv/mT0T3GKFNXbsqxSXkw+nnFmXnWq
            rql+GwbK5nF3aRxNK0iPNiEMRRbklSt2sJRK9fxi/Eoxj56aPqPRxQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gmpvctgh6axqpegek3h7c5kn0a5eumeksn5mscdha2w88ghenemsfg0cz2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRXhJcm5MaWNaWjdoL3I1
            YVJENjhCWTBrVjNRZFFFLzZhV1NyOWx6MEN3Cmc2TmVUc0Nldm90ZnFvNmlubDBE
            YjlqSTBTNHBSNUJFNHV6ZDl4RUVhVXMKLS0tIHpDS0N2MW9ueU5lK3FPQnpKdVJW
            dDROUmJ0MmQ3eCtYV2t6dUpramlXR3MKL5qJ+FbntN8PPS8lKO3s/+rtUGy5HlIc
            da5zsaHiWU9cw9EDk+awiAC0F5k/eKiakKBaLnPGNUwT4SRwptiI+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T08:52:49Z"
    mac: ENC[AES256_GCM,data:R3IaLYc0GA1MvTRvA5i8uOZmzQIteDbiE6Aet8cWov7b1DbcuVnXqS8hP+hYk0qVYQydb7G3YBX296xp8QGIqakVj+Dxpm9SMGiUCFuWNhZkoAb/UgblejjDYX+vC9LBf+bZUy179lPVT3lKai8teIvAeO1cNoVqyG10zZuh97M=,iv:mRe2OyH9opSjiEy8HzIRHRc/i8kjupuJzExvkH1OrHM=,tag:ALgd4bo1QzPKPp0lzjitEw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
