#ENC[AES256_GCM,data:u3Yna5Kq0k/puGCfpcYZa9a5JrVOK0y/zXcGllmkmg2b9FUCiDdWVr0JeIC0xSB1,iv:OMg4BoD3qTNSsFnb1opKOmRrMMLcJDBpmmqSjyvHkwQ=,tag:S8TDS3Ks9SSyEY8XY5l5Ww==,type:comment]
#ENC[AES256_GCM,data:u1eVHtG0ywlmfo2jrNNmBF84z1+LQi5xMQ==,iv:+tozwABJzRaqE9hnnqfu0uipCC2jFEwN+reJ3/f+sY4=,tag:DmV0gk7P6/rLV5NxErZwTg==,type:comment]
tailscale_auth_key: ENC[AES256_GCM,data:RoOiPLuqCATKuVko3uo1sbjHWxFCQdKmABUHxiR1RWYf+J64at0UdGjRckKBNtfUKHr1QY/Rz+ph/yzJKg==,iv:WITmsabyHlpoBt96apiPn6afavTZ3QhRSZsYB02qUNg=,tag:WI2U9wOrfqcrvuBVjgTyKg==,type:str]
sops:
    age:
        - recipient: age1ma7y9pzj5dk04j3jvjde3esfm6led6duludqk375k7hz93jc5a2scmw3ve
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZlB5UGc4Tlo0QVErWUIv
            MjV3TUIxUnZqN0Y3aUN0WW5qQUFzYWNpREdVCnNEVEZmekp4eFRIdloyTHdTeS9U
            b2xvNmJKbXJ6REVaK0ZDWGdjUEtDcWcKLS0tIDBaTDU5VWJsR3B1ZGYzdlNja05U
            TWx5dC93RFU5ZUQ4MEhaNWkzbUxodm8K2Fr2pViZTUNmhbrymBze9BKUHm58f8Q7
            /PWtzSIs/jH2s5/I8lfMs60og59EXumArt+VtfhZpLPUHzBrYqZbDw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ejn9t5mf6rmg3v708ejpdmjvrep3tspwx5tnlwkmepexzpt9349qrg7wq6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYkNmamg5bms0UTUxQWti
            YXRBZkZtdUhkTnpJUmNacGgvMmw2bWxaankwCnJBZEs3U2lvaUZVekJnVXNMSnkv
            TE04a1M2NXY5d2JGMXcrV24yWHBVREkKLS0tIDBMUDczK0pURENIR0ZwUW0xUDhC
            R0h1U2lkbWdlRE84b0VHMmh1SFZTK3MKZVRRMRZfl376oSG1DcVA+rx90G3jIH2r
            EDTzd0jwFQKQniwHyxU6IyWddCZvLqfwrQV/ISxlg9m1HuUbR485Aw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16z5lmvjvgsmtktqmpaz8x89nqg793fwzn274xcgz08kqa3tq3c9sr0nmyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDT0t4NklIRWhmanEzRHFr
            dGdlWGRwTXNoY29HYnRSMmhxN2tpTGVNdnlVCjIxMFlHRDZqVGJCb1gwRW1CREV3
            MklVY28vV2dDdHp5ek1zQzE3eC9zcFUKLS0tIHZJdzFJVWRuc0R5bXNPYXlZSElW
            eHp0amE2V3FsdUlSNXBNNnF3K2JqUUkK10xwkF2n5nCJReuhypkGWMvNxUY8t8YS
            1IqgupFW1X1hlDaCGtaBh90B1wLBeqmLDAr4LjJJz6e3cBWgfyW/oA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-29T20:11:13Z"
    mac: ENC[AES256_GCM,data:tdGSXldg+wHlQLEoJokiTjiLZj35d8EG290v2MilHsZhAhH36Z7lTqdGGAVBojjfImpYnVMsAcyynrtl7n5/7SnKd2N8Rnitx0N1VA1WUOavF2H8FNq5cM41lp+zj0N3Vsfi6AeOqxkLcUQbKwiE1bcFiIqta7LSmKZHjfOPHjY=,iv:8lFhXnfPa20aKV/p0FC3p4DnyVlE4oxNqmcMRKYoHs8=,tag:akkEO/gyMBsNQE143jeLEw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
